version: "3.0"
services:
  sink:
    container_name: z34_server2
    build: ./server
    tty: true
    cap_add:
    - NET_ADMIN
    hostname: z34_server2
    networks:
    - z34_network
  source:
    container_name: z34_client2
    build: ./client
    tty: true
    cap_add:
    - NET_ADMIN
    hostname: z34_client2
    networks:
    - z34_network
networks:
  z34_network:
    external: true
    name: z34_network
