version: '3'

services:
  server:
    build: .
    command: python -u src/server.py --host 0.0.0.0 --port 12345 --max-clients 10
    networks:
      - mini-tls-network
    ports:
      - "12345:12345"

  client1:
    build: .
    command: python -u src/client.py --host server --port 12345
    networks:
      - mini-tls-network
    depends_on:
      - server
    stdin_open: true
    tty: true

  client2:
    build: .
    command: python -u src/client.py --host server --port 12345
    networks:
      - mini-tls-network
    depends_on:
      - server
    stdin_open: true
    tty: true

  client3:
    build: .
    command: python -u src/client.py --host server --port 12345
    networks:
      - mini-tls-network
    depends_on:
      - server
    stdin_open: true
    tty: true

networks:
  mini-tls-network:
    driver: bridge